spring.application.name=ecommerce
spring.datasource.url=jdbc:mysql://root:FihxurmHGKgMqAMwOJzuLioGDnlEcZXL@crossover.proxy.rlwy.net:26885/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=FihxurmHGKgMqAMwOJzuLioGDnlEcZXL

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port==${PORT:8080}
